import type { Metadata } from "next";
import { Inter, Afacad, Sono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo, TopNav } from "../components/top-nav";
import { MobileNav } from "@/components/ui/mobile-nav";
import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { Icons } from "@/components/ui/icons";
import Navbar from "@/components/navbar";
import { Footer } from "@/components/footer";

//const inter = Inter({ subsets: ["latin"] });
//const afacad = Afacad({ subsets: ["latin"] });

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const afacad = Afacad({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-afacad",
});

const sono = Sono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sono-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${afacad.className}
        min-h-screen`}

        //        ${afacad.variable}
        //${sono.variable}
      >
        <header className="container flex items-center justify-start h-16">
          {/* <NavigationMenuDemo /> */}
          <Navbar />
          {/* <MobileNav /> */}
          {/* <div className="flex flex-1 items-center justify-between space-x-2 sm:justify-end">
            <div className="w-full flex-1 sm:w-auto sm:flex-none">
              <Link href={"/"}>ql-Commerce</Link>
            </div>
            <nav className="flex items-center">
              <Link href={"/"} target="_blank" rel="noreferrer">
                <div
                  className={cn(
                    buttonVariants({
                      variant: "ghost",
                    }),
                    "w-9 px-0"
                  )}
                >
                  <Icons.gitHub className="h-4 w-4" />
                  <span className="sr-only">GitHub</span>
                </div>
              </Link>
              <Link href={"/"} target="_blank" rel="noreferrer">
                <div
                  className={cn(
                    buttonVariants({
                      variant: "ghost",
                    }),
                    "w-9 px-0"
                  )}
                >
                  <Icons.twitter className="h-3 w-3 fill-current" />
                  <span className="sr-only">Twitter</span>
                </div>
              </Link>
              <ModeToggle /> 
            </nav>
          </div> */}
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
