import type { Metadata } from "next";
import { Inter, Afacad, Sono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo, TopNav } from "./_components/top-nav";

//const inter = Inter({ subsets: ["latin"] });
//const afacad = Afacad({ subsets: ["latin"] });

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const afacad = Afacad({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-afacad",
});

const sono = Sono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sono-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${afacad.className}
         `}

        //        ${afacad.variable}
        //${sono.variable}
      >
        <header className="px-24 flex items-center justify-start h-16">
          <NavigationMenuDemo />
        </header>
        {children}
      </body>
    </html>
  );
}
