import { Footer } from "@/components/footer";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Afacad, Roboto_Mono } from "next/font/google";
import "./globals.css";

const afacad = Afacad({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-afacad",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(afacad.className, roboto_mono.variable, "min-h-screen")}
      >
        <header className="container flex items-center justify-start h-16">
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
